<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <RootNamespace>EricksonLopez.Mapper.AotSmokeTest</RootNamespace>
    <AssemblyName>EricksonLopez.Mapper.AotSmokeTest</AssemblyName>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <StripSymbols>true</StripSymbols>
    <IsTestProject>false</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EricksonLopez.Mapper\EricksonLopez.Mapper.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Mapper.Generator\EricksonLopez.Mapper.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
