// Copyright © Erickson Lopez. MIT License.
using System;
using System.Collections.Immutable;
using System.Linq;
using AwesomeAssertions;
using EricksonLopez.Mapper.Generator;
using EricksonLopez.Mapper.Generator.Models;
using EricksonLopez.Mapper.Generator.Tests.Infrastructure;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace EricksonLopez.Mapper.Generator.Tests.Engine;

[Trait("Category", "FastAst")]
public class DependencyInjectionEmitterTests
{
    [Fact]
    public void GenerateDISource_WhenHasAttributeIsFalse_ShouldReturnNull()
    {
        var result = DependencyInjectionEmitter.GenerateDISource(ImmutableArray<TypeMapping>.Empty, false);
        result.Should().BeNull();
    }

    [Fact]
    public void GenerateDISource_WhenHasAttributeIsTrueAndEmptyMappings_ShouldReturnValidExtensionSkeleton()
    {
        var result = DependencyInjectionEmitter.GenerateDISource(ImmutableArray<TypeMapping>.Empty, true);
        result.Should().NotBeNull();
        result.Should().Contain("// <auto-generated/>");
        result.Should().Contain("#nullable enable");
        result.Should().Contain("using Microsoft.Extensions.DependencyInjection;");
        result.Should().Contain("namespace EricksonLopez.Mapper");
        result.Should().Contain("public static class MapperServiceCollectionExtensions");
        result.Should().Contain("public static IServiceCollection AddGeneratedMappers(this IServiceCollection services)");
        result.Should().Contain("return services;");

        var tree = CSharpSyntaxTree.ParseText(result!);
        var errors = tree.GetDiagnostics().Where(d => d.Severity == DiagnosticSeverity.Error).ToList();
        errors.Should().BeEmpty();
    }

    [Fact]
    public void GenerateDISource_WhenNonStaticMapper_ShouldRegisterSingleton()
    {
        var method = TestDataBuilders.CreateMethod("Map")
            .WithSourceType("Source")
            .WithTargetType("Dest")
            .Build();

        var mapper = TestDataBuilders.CreateType("OrderMapper")
            .WithNamespace("Orders.Mapping")
            .WithStatic(false)
            .AddMethod(method)
            .Build();

        var result = DependencyInjectionEmitter.GenerateDISource(ImmutableArray.Create(mapper), true);
        result.Should().Contain("services.AddSingleton<Orders.Mapping.OrderMapper>();");
    }

    [Fact]
    public void GenerateDISource_WhenStaticMapper_ShouldNotRegisterSingleton()
    {
        var method = TestDataBuilders.CreateMethod("Map")
            .WithSourceType("Source")
            .WithTargetType("Dest")
            .Build();

        var mapper = TestDataBuilders.CreateType("StaticOrderMapper")
            .WithNamespace("Orders.Mapping")
            .WithStatic(true)
            .AddMethod(method)
            .Build();

        var result = DependencyInjectionEmitter.GenerateDISource(ImmutableArray.Create(mapper), true);
        result.Should().NotContain("services.AddSingleton<Orders.Mapping.StaticOrderMapper>();");
    }

    [Fact]
    public void GenerateDISource_WhenCustomConvertersUsed_ShouldRegisterTransientDeduplicated()
    {
        var method1 = TestDataBuilders.CreateMethod("Map1")
            .WithSourceType("Source1")
            .WithTargetType("Dest1")
            .WithCustomConverter("Converters.DateConverter")
            .Build();

        var method2 = TestDataBuilders.CreateMethod("Map2")
            .WithSourceType("Source2")
            .WithTargetType("Dest2")
            .WithCustomConverter("Converters.DateConverter") // Duplicate
            .Build();

        var method3 = TestDataBuilders.CreateMethod("Map3")
            .WithSourceType("Source3")
            .WithTargetType("Dest3")
            .WithCustomConverter("Converters.MoneyConverter") // Distinct
            .Build();

        var mapper = TestDataBuilders.CreateType("OrderMapper")
            .WithNamespace("Orders.Mapping")
            .WithStatic(false)
            .AddMethod(method1)
            .AddMethod(method2)
            .AddMethod(method3)
            .Build();

        var result = DependencyInjectionEmitter.GenerateDISource(ImmutableArray.Create(mapper), true);
        result.Should().Contain("services.AddTransient<Converters.DateConverter>();");
        result.Should().Contain("services.AddTransient<Converters.MoneyConverter>();");

        // Verify deduplication
        var count = result!.Split(new[] { "services.AddTransient<Converters.DateConverter>();" }, StringSplitOptions.None).Length - 1;
        count.Should().Be(1);
    }
}
