<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject Condition="'$(MSBuildProjectName)' != 'EricksonLopez.Mapper.AotSmokeTest'">true</IsTestProject>
    <IsTestProject Condition="'$(MSBuildProjectName)' == 'EricksonLopez.Mapper.AotSmokeTest'">false</IsTestProject>
    <EnableTrimAnalyzer Condition="'$(PublishAot)' != 'true'">false</EnableTrimAnalyzer>
    <NoWarn>$(NoWarn);CA1847;CA1859;CA1860;CA1866;CA1310;CA2263;CA2012</NoWarn>
  </PropertyGroup>

  <ItemGroup Condition="Exists('$(MSBuildThisFileDirectory)xunit.runner.json')">
    <None Include="$(MSBuildThisFileDirectory)xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
