// Copyright © Erickson Lopez. MIT License.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace EricksonLopez.Mapper.Generator;

internal static class CodeEmitter
{
    public static string EscapeIdentifier(string name)
    {
        if (string.IsNullOrWhiteSpace(name)) return "_";
        var parts = name.Split('.');
        var resultParts = new List<string>();
        foreach (var p in parts)
        {
            string part = p;
            if (!SyntaxFacts.IsValidIdentifier(part))
            {
                var sb = new StringBuilder();
                if (part.Length > 0 && char.IsDigit(part[0])) sb.Append('_');
                foreach (char c in part)
                {
                    if (char.IsLetterOrDigit(c) || c == '_') sb.Append(c);
                    else sb.Append('_');
                }
                part = sb.ToString();
                if (string.IsNullOrEmpty(part)) part = "_";
            }
            if (SyntaxFacts.GetKeywordKind(part) != SyntaxKind.None || SyntaxFacts.GetContextualKeywordKind(part) != SyntaxKind.None)
            {
                part = "@" + part;
            }
            resultParts.Add(part);
        }
        return string.Join(".", resultParts);
    }

    public static string GenerateSourceCode(Models.TypeMapping typeMapping)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine($"namespace {EscapeIdentifier(typeMapping.Namespace)}");
        sb.AppendLine("{");
        sb.AppendLine($"    public{(typeMapping.IsStatic ? " static" : "")} partial class {EscapeIdentifier(typeMapping.ClassName)}");
        sb.AppendLine("    {");

        int counter = 1;
        foreach (var method in typeMapping.Methods)
        {
            string staticModifier = typeMapping.IsStatic ? "static " : "";
            sb.AppendLine($"        public {staticModifier}partial {method.TargetType.FullyQualifiedName} {method.MethodName}({method.SourceType.FullyQualifiedName} source)");
            sb.AppendLine("        {");
            if (!method.SourceType.IsValueType)
            {
                sb.AppendLine($"            if (source == null) throw new global::System.ArgumentNullException(nameof(source));");
            }

            if (method.CustomConverterField != null)
            {
                sb.AppendLine($"            return this.{method.CustomConverterField}.Convert(source);");
                sb.AppendLine("        }");
                sb.AppendLine();
                continue;
            }

            if (method.CustomConverter != null)
            {
                sb.AppendLine($"            var converter = new {method.CustomConverter}();");
                sb.AppendLine("            return converter.Convert(source);");
                sb.AppendLine("        }");
                sb.AppendLine();
                continue;
            }

            var preStatements = new StringBuilder();

            if (method.Members.Count == 1 && method.Members[0].TargetName == "")
            {
                var enumMember = method.Members[0];
                string expr = GenerateConversionExpression("source", enumMember.Strategy, preStatements, ref counter, typeMapping.IsStatic);
                sb.Append(preStatements);
                sb.AppendLine($"            return {expr};");
                sb.AppendLine("        }");
                sb.AppendLine();
                continue;
            }

            var propExpressions = new Dictionary<string, string>();
            foreach (var prop in method.Members)
            {
                if (prop.CustomValueExpression != null)
                {
                    propExpressions[prop.TargetName] = prop.CustomValueExpression;
                    continue;
                }

                string sourceAccessor = prop.CustomSourceExpression != null
                    ? prop.CustomSourceExpression
                    : $"source.{EscapeIdentifier(prop.SourceName)}";

                if (prop.Fallback != null) sourceAccessor = $"({sourceAccessor} ?? {prop.Fallback})";
                propExpressions[prop.TargetName] = GenerateConversionExpression(sourceAccessor, prop.Strategy, preStatements, ref counter, typeMapping.IsStatic);
            }

            var paramExpressions = new Dictionary<string, string>();
            if (method.Construction is Models.ConstructionStrategy.ParameterizedConstructor pCtor)
            {
                foreach (var param in pCtor.Parameters)
                {
                    if (param.CustomValueExpression != null)
                    {
                        paramExpressions[param.TargetName] = param.CustomValueExpression;
                        continue;
                    }

                    string sourceAccessor = param.CustomSourceExpression != null
                        ? param.CustomSourceExpression
                        : $"source.{EscapeIdentifier(param.SourceName)}";

                    if (param.Fallback != null) sourceAccessor = $"({sourceAccessor} ?? {param.Fallback})";
                    paramExpressions[param.TargetName] = GenerateConversionExpression(sourceAccessor, param.Strategy, preStatements, ref counter, typeMapping.IsStatic);
                }
            }
            else if (method.Construction is Models.ConstructionStrategy.FactoryMethod fMeth)
            {
                foreach (var param in fMeth.Parameters)
                {
                    if (param.CustomValueExpression != null)
                    {
                        paramExpressions[param.TargetName] = param.CustomValueExpression;
                        continue;
                    }

                    string sourceAccessor = param.CustomSourceExpression != null
                        ? param.CustomSourceExpression
                        : $"source.{EscapeIdentifier(param.SourceName)}";

                    if (param.Fallback != null) sourceAccessor = $"({sourceAccessor} ?? {param.Fallback})";
                    paramExpressions[param.TargetName] = GenerateConversionExpression(sourceAccessor, param.Strategy, preStatements, ref counter, typeMapping.IsStatic);
                }
            }

            if (method.DerivedTypes.Count > 0)
            {
                sb.AppendLine("            switch (source)");
                sb.AppendLine("            {");
                foreach (var derived in method.DerivedTypes)
                {
                    if (derived.MethodName != null)
                    {
                        sb.AppendLine($"                case {derived.SourceType} derivedSource: return {derived.MethodName}(derivedSource);");
                    }
                    else
                    {
                        sb.AppendLine($"                case {derived.SourceType} derivedSource: throw new global::System.InvalidOperationException(\"No mapping method defined for {derived.SourceType} to {derived.TargetType}\");");
                    }
                }
                sb.AppendLine("            }");

                if (method.TargetType.IsAbstract)
                {
                    sb.AppendLine($"            throw new global::System.InvalidOperationException($\"Cannot instantiate abstract base type {method.TargetType.FullyQualifiedName}. Not all derived types were covered.\");");
                    sb.AppendLine("        }");
                    continue;
                }
            }

            sb.Append(preStatements);

            if (method.Construction is Models.ConstructionStrategy.ObjectInitializer)
            {
                sb.AppendLine($"            var target = new {method.TargetType.FullyQualifiedName}()");
                if (method.Members.Count > 0)
                {
                    sb.AppendLine("            {");
                    foreach (var prop in method.Members)
                    {
                        sb.AppendLine($"                {EscapeIdentifier(prop.TargetName)} = {propExpressions[prop.TargetName]},");
                    }
                    sb.AppendLine("            };");
                }
                else
                {
                    sb.AppendLine("            ;");
                }
                sb.AppendLine("            return target;");
            }
            else if (method.Construction is Models.ConstructionStrategy.ParameterizedConstructor pCtorParam)
            {
                sb.Append($"            var target = new {method.TargetType.FullyQualifiedName}(");
                sb.Append(string.Join(", ", pCtorParam.Parameters.Select(p => paramExpressions[p.TargetName])));
                sb.AppendLine(")");

                if (method.Members.Count > 0)
                {
                    sb.AppendLine("            {");
                    foreach (var prop in method.Members)
                    {
                        sb.AppendLine($"                {EscapeIdentifier(prop.TargetName)} = {propExpressions[prop.TargetName]},");
                    }
                    sb.AppendLine("            };");
                }
                else
                {
                    sb.AppendLine("            ;");
                }

                sb.AppendLine("            return target;");
            }
            else if (method.Construction is Models.ConstructionStrategy.FactoryMethod fMethParam)
            {
                sb.Append($"            var target = {method.TargetType.FullyQualifiedName}.{fMethParam.MethodName}(");
                sb.Append(string.Join(", ", fMethParam.Parameters.Select(p => paramExpressions[p.TargetName])));
                sb.AppendLine(")");

                if (method.Members.Count > 0)
                {
                    sb.AppendLine("            {");
                    foreach (var prop in method.Members)
                    {
                        sb.AppendLine($"                {EscapeIdentifier(prop.TargetName)} = {propExpressions[prop.TargetName]},");
                    }
                    sb.AppendLine("            };");
                }
                else
                {
                    sb.AppendLine("            ;");
                }

                sb.AppendLine("            return target;");
            }

            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GenerateConversionExpression(string sourceAccessor, Models.ConversionStrategy strategy, StringBuilder preStatements, ref int counter, bool isStaticMapper)
    {
        if (strategy is Models.ConversionStrategy.BuiltinConversion builtinConv)
        {
            return builtinConv.ExpressionTemplate.Replace("{0}", sourceAccessor);
        }
        if (strategy is Models.ConversionStrategy.MapMethodInvocation methodInv)
        {
            if (methodInv.IsSourceNullable && methodInv.IsTargetNullable)
            {
                return isStaticMapper
                    ? $"({sourceAccessor} != null ? {methodInv.MethodName}({sourceAccessor}) : null)"
                    : $"({sourceAccessor} != null ? this.{methodInv.MethodName}({sourceAccessor}) : null)";
            }
            return isStaticMapper ? $"{methodInv.MethodName}({sourceAccessor})" : $"this.{methodInv.MethodName}({sourceAccessor})";
        }
        if (strategy is Models.ConversionStrategy.ValueObjectMapping voMap)
        {
            string innerExp = GenerateConversionExpression(sourceAccessor, voMap.InnerStrategy, preStatements, ref counter, isStaticMapper);
            if (voMap.Kind == 0) // Target has 1-param constructor
            {
                return $"new {voMap.TargetInnerType}({innerExp})";
            }
            else if (voMap.Kind == 1) // Source has Value property
            {
                string propExp = $"{sourceAccessor}.Value";
                return GenerateConversionExpression(propExp, voMap.InnerStrategy, preStatements, ref counter, isStaticMapper);
            }
            else
            {
                return $"({voMap.TargetInnerType}){innerExp}";
            }
        }
        if (strategy is Models.ConversionStrategy.EnumerableMapping envMap)
        {
            string targetVar = $"_col{counter++}";
            string sourceVar = $"_src{counter}";

            string countExpr = (envMap.SourceIsArray || envMap.SourceIsImmutableArray) ? $"{sourceAccessor}.Length" : (envMap.SourceHasCount ? $"{sourceAccessor}.Count" : "");
            string targetType;
            string targetInst;

            if (envMap.IsArray)
            {
                targetType = $"{envMap.TargetElementType}[]";
                targetInst = $"new {envMap.TargetElementType}[{sourceAccessor}.Length]";
                preStatements.AppendLine($"            {targetType} {targetVar} = global::System.Array.Empty<{envMap.TargetElementType}>();");
            }
            else if (envMap.IsImmutableArray)
            {
                targetType = $"global::System.Collections.Immutable.ImmutableArray<{envMap.TargetElementType}>";
                targetInst = string.IsNullOrEmpty(countExpr)
                    ? $"(global::System.Linq.Enumerable.TryGetNonEnumeratedCount({sourceAccessor}, out int _c{counter}) ? global::System.Collections.Immutable.ImmutableArray.CreateBuilder<{envMap.TargetElementType}>(_c{counter}) : global::System.Collections.Immutable.ImmutableArray.CreateBuilder<{envMap.TargetElementType}>())"
                    : $"global::System.Collections.Immutable.ImmutableArray.CreateBuilder<{envMap.TargetElementType}>({countExpr})";
                preStatements.AppendLine($"            {targetType} {targetVar} = global::System.Collections.Immutable.ImmutableArray<{envMap.TargetElementType}>.Empty;");
            }
            else if (envMap.IsImmutableList)
            {
                targetType = $"global::System.Collections.Immutable.ImmutableList<{envMap.TargetElementType}>";
                targetInst = $"global::System.Collections.Immutable.ImmutableList.CreateBuilder<{envMap.TargetElementType}>()";
                preStatements.AppendLine($"            {targetType} {targetVar} = global::System.Collections.Immutable.ImmutableList<{envMap.TargetElementType}>.Empty;");
            }
            else if (envMap.IsFrozenSet)
            {
                targetType = $"global::System.Collections.Frozen.FrozenSet<{envMap.TargetElementType}>";
                targetInst = $"new global::System.Collections.Generic.HashSet<{envMap.TargetElementType}>({countExpr})";
                preStatements.AppendLine($"            {targetType}? {targetVar} = null;");
            }
            else if (envMap.IsHashSet)
            {
                targetType = $"global::System.Collections.Generic.HashSet<{envMap.TargetElementType}>";
                targetInst = $"new global::System.Collections.Generic.HashSet<{envMap.TargetElementType}>({countExpr})";
                preStatements.AppendLine($"            {targetType}? {targetVar} = null;");
            }
            else
            {
                targetType = $"global::System.Collections.Generic.List<{envMap.TargetElementType}>";
                targetInst = string.IsNullOrEmpty(countExpr)
                    ? $"(global::System.Linq.Enumerable.TryGetNonEnumeratedCount({sourceAccessor}, out int _c{counter}) ? new global::System.Collections.Generic.List<{envMap.TargetElementType}>(_c{counter}) : new global::System.Collections.Generic.List<{envMap.TargetElementType}>())"
                    : $"new global::System.Collections.Generic.List<{envMap.TargetElementType}>({countExpr})";
                preStatements.AppendLine($"            {targetType}? {targetVar} = null;");
            }

            bool requiresNullCheck = !envMap.SourceIsValueType;
            bool requiresIsDefaultCheck = envMap.SourceIsImmutableArray;

            if (requiresNullCheck)
            {
                preStatements.AppendLine($"            if ({sourceAccessor} != null)");
                preStatements.AppendLine("            {");
            }
            else if (requiresIsDefaultCheck)
            {
                preStatements.AppendLine($"            if (!{sourceAccessor}.IsDefault)");
                preStatements.AppendLine("            {");
            }

            if (envMap.IsArray)
            {
                preStatements.AppendLine($"                {targetVar} = {targetInst};");
                preStatements.AppendLine($"                for (int i = 0; i < {sourceAccessor}.Length; i++)");
                preStatements.AppendLine("                {");
                string innerExp = GenerateConversionExpression($"{sourceAccessor}[i]", envMap.ElementStrategy, preStatements, ref counter, isStaticMapper);
                preStatements.AppendLine($"                    {targetVar}[i] = {innerExp};");
                preStatements.AppendLine("                }");
            }
            else if (envMap.IsFrozenSet)
            {
                string frozenBuilderVar = $"_frozenBuilder{counter}";
                preStatements.AppendLine($"                var {frozenBuilderVar} = {targetInst};");
                preStatements.AppendLine($"                foreach (var {sourceVar} in {sourceAccessor})");
                preStatements.AppendLine("                {");
                string innerExp = GenerateConversionExpression(sourceVar, envMap.ElementStrategy, preStatements, ref counter, isStaticMapper);
                preStatements.AppendLine($"                    {frozenBuilderVar}.Add({innerExp});");
                preStatements.AppendLine("                }");
                preStatements.AppendLine($"                {targetVar} = global::System.Collections.Frozen.FrozenSet.ToFrozenSet({frozenBuilderVar});");
            }
            else
            {
                bool usesBuilder = envMap.IsImmutableArray || envMap.IsImmutableList;
                string builderVar = usesBuilder ? $"_builder{counter}" : targetVar;
                if (usesBuilder)
                {
                    preStatements.AppendLine($"                var {builderVar} = {targetInst};");
                }
                else
                {
                    preStatements.AppendLine($"                {targetVar} = {targetInst};");
                }

                preStatements.AppendLine($"                foreach (var {sourceVar} in {sourceAccessor})");
                preStatements.AppendLine("                {");
                string innerExp = GenerateConversionExpression(sourceVar, envMap.ElementStrategy, preStatements, ref counter, isStaticMapper);
                preStatements.AppendLine($"                    {builderVar}.Add({innerExp});");
                preStatements.AppendLine("                }");

                if (envMap.IsImmutableArray || envMap.IsImmutableList)
                {
                    preStatements.AppendLine($"                {targetVar} = {builderVar}.ToImmutable();");
                }
            }
            if (requiresNullCheck || requiresIsDefaultCheck)
            {
                preStatements.AppendLine("            }");
            }

            return targetVar;
        }
        if (strategy is Models.ConversionStrategy.DictionaryMapping dictMap)
        {
            string targetVar = $"_dict{counter++}";
            string kvpVar = $"_kvp{counter}";
            string targetType = $"global::System.Collections.Generic.Dictionary<{dictMap.TargetKeyType}, {dictMap.TargetValueType}>";

            string dictCountExpr = dictMap.SourceHasCount ? $"{sourceAccessor}.Count" : string.Empty;
            string dictInst = string.IsNullOrEmpty(dictCountExpr)
                ? $"(global::System.Linq.Enumerable.TryGetNonEnumeratedCount({sourceAccessor}, out int _dc{counter}) ? new {targetType}(_dc{counter}) : new {targetType}())"
                : $"new {targetType}({dictCountExpr})";

            preStatements.AppendLine($"            {targetType}? {targetVar} = null;");
            preStatements.AppendLine($"            if ({sourceAccessor} != null)");
            preStatements.AppendLine("            {");
            preStatements.AppendLine($"                {targetVar} = {dictInst};");
            preStatements.AppendLine($"                foreach (var {kvpVar} in {sourceAccessor})");
            preStatements.AppendLine("                {");
            string innerKeyExp = GenerateConversionExpression($"{kvpVar}.Key", dictMap.KeyStrategy, preStatements, ref counter, isStaticMapper);
            string innerValueExp = GenerateConversionExpression($"{kvpVar}.Value", dictMap.ValueStrategy, preStatements, ref counter, isStaticMapper);
            preStatements.AppendLine($"                    {targetVar}[{innerKeyExp}] = {innerValueExp};");
            preStatements.AppendLine("                }");
            preStatements.AppendLine("            }");

            return targetVar;
        }

        return sourceAccessor;
    }
}
