// Copyright © Erickson Lopez. MIT License.
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace EricksonLopez.Mapper.Generator;

internal static class DependencyInjectionEmitter
{
    public static string? GenerateDISource(ImmutableArray<Models.TypeMapping> mappings, bool hasAttribute)
    {
        if (!hasAttribute) return null;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace EricksonLopez.Mapper");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Provides extension methods for registering compile-time generated mappers into an <see cref=\"IServiceCollection\"/>.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class MapperServiceCollectionExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Registers all compile-time generated mappers in the compilation into the specified <see cref=\"IServiceCollection\"/>.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <param name=\"services\">The service collection to add mappers to.</param>");
        sb.AppendLine("        /// <returns>The same service collection instance so that multiple calls can be chained.</returns>");
        sb.AppendLine("        public static IServiceCollection AddGeneratedMappers(this IServiceCollection services)");
        sb.AppendLine("        {");

        var customConverters = new HashSet<string>();
        foreach (var map in mappings)
        {
            if (!map.IsStatic)
            {
                string typeName = string.IsNullOrWhiteSpace(map.Namespace)
                    ? CodeEmitter.EscapeIdentifier(map.ClassName)
                    : $"{CodeEmitter.EscapeIdentifier(map.Namespace)}.{CodeEmitter.EscapeIdentifier(map.ClassName)}";
                sb.AppendLine($"            services.AddSingleton<{typeName}>();");
            }
            foreach (var method in map.Methods)
            {
                if (method.CustomConverter != null)
                {
                    customConverters.Add(method.CustomConverter);
                }
            }
        }

        foreach (var conv in customConverters)
        {
            sb.AppendLine($"            services.AddTransient<{conv}>();");
        }

        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static void EmitDIRegistration(ImmutableArray<Models.TypeMapping> mappings, bool hasAttribute, SourceProductionContext context)
    {
        var source = GenerateDISource(mappings, hasAttribute);
        if (source != null)
        {
            context.AddSource("MapperServiceCollectionExtensions.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }
}

