// Copyright © Erickson Lopez. MIT License.
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading;
using System.Threading.Tasks;
using EricksonLopez.Mapper.Generator.Tests.Infrastructure;
using Microsoft.CodeAnalysis;
using Xunit;

namespace EricksonLopez.Mapper.Generator.Tests.Features;

/// <summary>
/// Contains snapshot-based unit tests that verify the code generated by <see cref="EricksonLopez.Mapper.Generator.MapperGenerator"/>
/// for core mapping scenarios (properties, records, structs, generics).
/// </summary>
[Trait("Category", "Snapshot")]
public partial class MapperGeneratorTests
{
    [Fact]
    public async Task Generate_WhenSimpleProperties_ShouldCreateCorrectMapping()
    {
        var source = @"
using EricksonLopez.Mapper;

namespace TestNamespace;

public class User
{
    public string Name { get; set; }
    public int Age { get; set; }
}

public class UserDto
{
    public string Name { get; set; }
    public int Age { get; set; }
}

[Mapper]
public partial class UserMapper
{
    public partial UserDto ToDto(User source);
}
";
        await RunGeneratorAndVerify(source);
    }

    [Fact]
    public async Task Generate_WhenRecordWithConstructor_ShouldCreateCorrectMapping()
    {
        var source = @"

namespace TestNamespace;

public class User
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public int Age { get; set; }
}

public record UserDto(string FirstName, string LastName)
{
    public int Age { get; set; }
}

[Mapper]
public partial class UserMapper
{
    public partial UserDto ToDto(User source);
}
";
        await RunGeneratorAndVerify(source);
    }

    [Fact]
    public async Task Generate_WhenInitOnlyProperties_ShouldCreateCorrectMapping()
    {
        var source = @"
namespace TestNamespace;
public class Source { public string Name { get; set; } }
public class Dest 
{ 
    public string Name { get; init; } 
}
[Mapper]
public partial class Mapper
{
    public partial Dest Map(Source source);
}
";
        await RunGeneratorAndVerify(source);
    }

    [Fact]
    public async Task Generate_WhenGenericTypeMapping_ShouldCreateCorrectMapping()
    {
        var source = @"
namespace TestNamespace;
public class Source<T> { public T Data { get; set; } }
public class Dest<T> { public T Data { get; set; } }
[Mapper]
public partial class Mapper
{
    public partial Dest<string> Map(Source<string> source);
}
";
        await RunGeneratorAndVerify(source);
    }

    [Fact]
    public async Task Generate_WhenComplexGenericMapper_ShouldMapCorrectly()
    {
        var source = @"
namespace TestNamespace;
public class Paged<T> { public int Total { get; set; } public List<T> Items { get; set; } }
public class Source { public string Name { get; set; } }
public class Dest { public string Name { get; set; } }
[Mapper]
public partial class Mapper
{
    public partial Dest MapDest(Source source);
    public partial Paged<TDest> MapPaged<TSource, TDest>(Paged<TSource> source);
}
";
        await RunGeneratorAndVerify(source);
    }

    [Fact]
    public async Task Generate_WhenInterfaceProperties_ShouldMapSuccessfully()
    {
        var source = @"
namespace TestNamespace;
public interface IBaseSource { string BaseVal { get; set; } }
public interface ISource : IBaseSource { string Val { get; set; } }
public class Dest { public string Val { get; set; } public string BaseVal { get; set; } }
[Mapper]
public partial class Mapper
{
    public partial Dest Map(ISource source);
}
";
        await RunGeneratorAndVerify(source);
    }

    [Fact]
    public async Task Generate_WhenStructMapping_ShouldMapCorrectly()
    {
        var source = @"

namespace TestNamespace;

public struct PointSource { public int X { get; set; } public int Y { get; set; } }
public readonly struct PointDest 
{ 
    public int X { get; } 
    public int Y { get; } 
    public PointDest(int x, int y) { X = x; Y = y; } 
}

[Mapper]
public partial class Mapper
{
    public partial PointDest Map(PointSource source);
}
";
        await RunGeneratorAndVerify(source);
    }

    [Fact]
    public async Task Generate_WhenEmptyClass_ShouldMapSuccessfully()
    {
        var source = @"
namespace TestNamespace;
public class Source { }
public class Dest { }
[Mapper]
public partial class Mapper
{
    public partial Dest Map(Source source);
}
";
        await RunGeneratorAndVerify(source);
    }

    private static async Task RunGeneratorAndVerify(
        string source,
        [System.Runtime.CompilerServices.CallerMemberName] string testName = "",
        [System.Runtime.CompilerServices.CallerFilePath] string filePath = "")
    {
        await GeneratorTestHelper.RunGeneratorAndVerify(source, testName, filePath);
    }

    private static (ImmutableArray<Diagnostic> Diagnostics, string Output) RunGeneratorSimple(string source)
    {
        return GeneratorTestHelper.RunGeneratorSimple(source);
    }
}



